### ISSUE TITLE
Can you produce a version of dart?

### ISSUE THREAD

**Issue by gavin1995** [cierelabs/json-complete#16]
This library is very good, if you want to produce a dart version of the library, I am willing to work with you. 😺

**Comment by dwighthouse** [comment]
I am not in a position to produce a Dart version, since I don't know or use Dart. However, if you wish to port the library to Dart, I would be happy to link to it.

As a suggestion: Focus on compatibility of types as the primary concern. The json-complete doctrine for types that aren't directly compatible is to store the different implementations as different types, and then provide conversion scripts to smooth out the differences between them.
